---
title: "10_ANOVA_total_biomass"
author: "Francisca Rodriguez"
date: "12/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Post-decontamination**
```{r}
#load libraries
library(tidyverse)
library(car)
library(ggpubr)
library(effects)
library(readxl)
library(emmeans)

dat = read_excel("./pips_data/pips_complete.xlsx") |>
  mutate(
    Inoculation = as.character(Inoculation),
    Water = as.character(Water)
  )
```

**Outlier analysis: total biomass**
```{r}
#additive model
biomass_mod = aov(WeightGrams ~ Inoculation + Water, data = dat)
Anova(biomass_mod, type = "2")

# Studentized residuals
MASS::studres(biomass_mod) |>
  abs() |>
  sort()

#remove the outliers, re-run the analysis
filtered_biomass = dat[-c(182, 36, 198), ]
```

**ANOVA: total biomass**
```{r}
#additive model
biomass_mod1 = aov(WeightGrams ~ InoculationLabeled + WaterLabeled, data = filtered_biomass)
Anova(biomass_mod1, type = "2")

#interactive model
biomass_mod2 = aov(WeightGrams ~ InoculationLabeled * WaterLabeled, data = filtered_biomass)
Anova(biomass_mod2, type = "3")
```

**Post-hoc test: total biomass**
```{r}
#planned comparison test

#Inoculation
#apply the emmeans() command to the ANOVA object.
BiomassPairs1 <- emmeans(biomass_mod1, ~ InoculationLabeled)

#obtain the planned 95% confidence intervals for a pairwise comparison
BiomassPlanned1 <- contrast(BiomassPairs1, adjust = "none")
BiomassPlanned1

#Water
#apply the emmeans() command to the ANOVA object.
BiomassPairs2 <- emmeans(biomass_mod2, ~ WaterLabeled)

#obtain the planned 95% confidence intervals for a pairwise comparison
BiomassPlanned2 <- contrast(BiomassPairs2, adjust = "none")
BiomassPlanned2

```

**Outlier analysis: below-ground biomass**
```{r}
bio_root = subset(dat, Type == "Root")
  
#interaction model
root_mass1= aov(WeightGrams ~ Inoculation * Water, data = bio_root)
Anova(root_mass1, type = "3") # if you have interactions, type-3 sums-of-squares is appropriate

#additive model
root_mass2 = aov(WeightGrams ~ Inoculation + Water, data = bio_root)
Anova(root_mass2, type = "2")

#plot to check residuals
plot(root_mass1)
plot(root_mass2)

# Studentized residuals
MASS::studres(root_mass1) |>
  abs() |>
  sort()

#remove the outliers, re-run the analysis
filtered_root = bio_root[-c(193), ]

```

**Outlier analysis: above-ground biomass**
```{r}
bio_shoot = subset(dat, Type == "Shoot")

#interaction model
shoot_mass1 = aov(WeightGrams ~ Inoculation * Water, data = bio_shoot)
Anova(shoot_mass1, type = "3") # if you have interactions, type-3 sums-of-squares is appropriate

#additive model
shoot_mass2 = aov(WeightGrams ~ Inoculation + Water, data = bio_shoot)
Anova(shoot_mass2, type = "2")

#plot to check residuals
plot(shoot_mass1)
plot(shoot_mass2)

# Studentized residuals
MASS::studres(shoot_mass1) |>
  abs() |>
  sort()

#remove the outliers, re-run the analysis
filtered_shoot = bio_shoot[-c(182), ]
```

**ANOVA: below-ground biomass**
```{r}
#interaction model
root_mass1= aov(WeightGrams ~ InoculationLabeled * WaterLabeled, data = filtered_root)
Anova(root_mass1, type = "3") # if you have interactions, type-3 sums-of-squares is appropriate
plot(root_mass1, main = "Root")
plot(allEffects(root_mass1))

#additive model
root_mass2 = aov(WeightGrams ~ InoculationLabeled + WaterLabeled, data = filtered_root)
Anova(root_mass2, type = "2")
plot(root_mass2, main = "Root")
plot(allEffects(root_mass2))
```

**Post-hoc test: below-ground biomass**
```{r}
## Type III ANOVA ##

#apply the emmeans() command to the ANOVA object.
RootsW1<- emmeans(root_mass1, ~ WaterLabeled)
RootsW1

#obtain the planned 95% confidence intervals for a pairwise comparison
RootsPlannedW1 <- contrast(RootsW1, adjust = "none")
RootsPlannedW1

#apply the emmeans() command to the ANOVA object.
RootsI1<- emmeans(root_mass1, ~ InoculationLabeled)
RootsI1

#obtain the planned 95% confidence intervals for a pairwise comparison
RootsPlannedI1 <- contrast(RootsI1, adjust = "none")
RootsPlannedI1

## Type II ANOVA ##

#apply the emmeans() command to the ANOVA object.
RootsW2<- emmeans(root_mass2, ~ WaterLabeled)
RootsW2

#obtain the planned 95% confidence intervals for a pairwise comparison
RootsPlannedW2 <- contrast(RootsW2, adjust = "none")
RootsPlannedW2

#apply the emmeans() command to the ANOVA object.
RootsI2<- emmeans(root_mass2, ~ InoculationLabeled)
RootsI2

#obtain the planned 95% confidence intervals for a pairwise comparison
RootsPlannedI2 <- contrast(RootsI2, adjust = "none")
RootsPlannedI2
```


**ANOVA: above-ground biomass**
```{r}
#interaction model
shoot_mass1 = aov(WeightGrams ~ InoculationLabeled * WaterLabeled, data = filtered_shoot)
Anova(shoot_mass1, type = "3") # if you have interactions, type-3 sums-of-squares is appropriate
plot(shoot_mass1, main = "Shoot")
plot(allEffects(shoot_mass1))

#additive model
shoot_mass2 = aov(WeightGrams ~ InoculationLabeled + WaterLabeled, data = filtered_shoot)
Anova(shoot_mass2, type = "2")
plot(shoot_mass2, main = "Shoot")
plot(allEffects(shoot_mass2))
```

**Post-hoc test: above-ground biomass**
```{r}
## Type III ANOVA ##

#apply the emmeans() command to the ANOVA object.
ShootsW1<- emmeans(shoot_mass1, ~ WaterLabeled)
ShootsW1

#obtain the planned 95% confidence intervals for a pairwise comparison
ShootsPlannedW1 <- contrast(ShootsW1, adjust = "none")
ShootsPlannedW1

#apply the emmeans() command to the ANOVA object.
ShootsI1<- emmeans(shoot_mass1, ~ InoculationLabeled)
ShootsI1

#obtain the planned 95% confidence intervals for a pairwise comparison
ShootsPlannedI1 <- contrast(ShootsI1, adjust = "none")
ShootsPlannedI1

## Type II ANOVA ##

#apply the emmeans() command to the ANOVA object.
ShootsW2<- emmeans(shoot_mass2, ~ WaterLabeled)
ShootsW2

#obtain the planned 95% confidence intervals for a pairwise comparison
ShootsPlannedW2 <- contrast(ShootsW2, adjust = "none")
ShootsPlannedW2

#apply the emmeans() command to the ANOVA object.
ShootsI2<- emmeans(shoot_mass2, ~ InoculationLabeled)
ShootsI2

#obtain the planned 95% confidence intervals for a pairwise comparison
ShootsPlannedI2 <- contrast(ShootsI2, adjust = "none")
ShootsPlannedI2
```

