---
title: "Keck Microbiome"
author: "C Wall"
date: "8/31/2020"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 4
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---

```{r global options, results="hide", warning=FALSE, message=FALSE}
if (!require('knitr')) install.packages('knitr'); library('knitr')
knitr::opts_chunk$set(warning=FALSE, message=FALSE, fig.align='center')

# Load in packages
if (!require("pacman")) install.packages("pacman"); library(pacman) # for rapid install if not in library
if(!requireNamespace("BiocManager", quietly = TRUE))
	install.packages("BiocManager")	#Load packages from Bioconductor

pacman::p_load('FedData', 'latticeExtra', 'scales', 'viridis', 'ggmap', 'phyloseq', 'raster', 'rgdal', 'RColorBrewer', 'ggplot2', 'vegan', 'ggplot2', 'phyloseq', 'bipartite', 'plotrix', 'viridis', 'lattice', 'fossil', 'plyr', 'devtools', 'ggpubr', 'gridExtra', 'cowplot', 'rgr', 'ggplot2', 'cowplot')
 

data<-as.matrix(read.csv("data/inoculum test/abundance_table_97.csv", header = TRUE, row.names = 1))

OTU = otu_table(data, taxa_are_rows = TRUE)

#bar plot
barplot(OTU, cex.axis=0.6, cex.names=0.6)

#rarifaction curve
# use data matrix, transposes as rows as samples and columns at OTUs
rarecurve(t(data), step=100, cex=0.5, label=FALSE, col="blue", main="ITS: inoc.trial",
                   xlim=c(0, 100000), ylab="samples")
abline(v = 26000, col="gray50", lwd=2, lty=2)
dev.print(pdf, "figures/rarecurve.pdf", width=7, height=4)
dev.off()

S<-specnumber(OTU) # observed number of species
(raremax <- max(rowSums(OTU))) # max OTUs
Srare <- rarefy(OTU, (0.4*raremax)) #rarefy to 40% max
plot(S, Srare, xlab = "Observed No. of Species", ylab = "Rarefied No. of Species")
abline(0, 1)
rarecurve(OTU, step = 20, sample = 0.4*raremax, col = "blue", cex = 0.6, label=FALSE)


# richness table
ITS.rich<-estimate_richness(OTU, measures="Observed")

# richness plot
spec_rich_hab = plot_richness(OTU, measures="Observed")
spec_rich_hab

dev.copy(pdf, "figures/spec_rich_hab.pdf", height=4, width=6)
dev.off() 

```

```{r, LiCor}
### Licor data for the plants Feb 16th

Licor<-read.csv("data/LiCor/Licor_R.csv", header = TRUE)
Licor$iWUE<-Licor$A/Licor$gsw
Licor$insWUE<-Licor$A/Licor$E

# remove all negative and zero values in dataframe to NA
# to replace any numeric coded values, e.g., -9999 with NAs, set coded = -9999
Licor2 <- ltdl.fix.df(Licor, negs2na = TRUE, coded = -9999, zero2na = TRUE)

box_plot.E <- ggplot(Licor2, aes(x = trt, y = E)) +
  xlab("") +
  geom_boxplot(aes(fill=trt)) + theme_classic()

box_plot.A <- ggplot(Licor2, aes(x = trt, y = A)) +
  xlab("") +
  geom_boxplot(aes(fill=trt)) + theme_classic()

box_plot.gsw <- ggplot(Licor2, aes(x = trt, y = gsw)) +
  xlab("") +
  geom_boxplot(aes(fill=trt)) + theme_classic()

box_plot.iWUE <- ggplot(Licor2, aes(x = trt, y = iWUE)) +
  ylab("iWUE (A/gsw)") +
  xlab("Treatment") +
  geom_boxplot(aes(fill=trt)) + theme_classic()

box_plot.insWUE <- ggplot(Licor2, aes(x = trt, y = insWUE)) +
  ylab("insWUE (A/E)") +
  xlab("Treatment") +
  geom_boxplot(aes(fill=trt)) + theme_classic()

plot_grid(box_plot.E, box_plot.A, box_plot.gsw, box_plot.iWUE, box_plot.insWUE, labels = c('A', 'B', 'C', 'D', 'E'))

dev.copy(pdf, "data/LiCor/output.plots.pdf", height=5, width=8)
dev.off()

```


