---
title: "Phyloseq"
author: "Francisca Rodriguez"
date: "11/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Data input**
```{r}

#load libraries 
library(phyloseq)
library(tibble)
library(dplyr)

#Load seqtable.nochim and taxa from dada2 files from Kacie
seqtable.nochim <- readRDS('./raw_data/dada2_seqtable.RDS')
taxa <- readRDS('./raw_data/RDP_Taxonomy_from_dada2.RDS')
strawb_miseq_map <- read.csv("./raw_data/Strawberry_Miseq_Map_forQIIME.csv", fileEncoding="UTF-8-BOM")

# add empty column
strawb_miseq_map <- add_column(strawb_miseq_map, SampleType = NA)

# get rid of unneeded cols
strawb_miseq_map <- select(strawb_miseq_map, 
                           SampleID, 
                           TimePoint, 
                           Type, 
                           PlantID, 
                           WeightGrams, 
                           SampleNotes, 
                           Water, 
                           Inoculation, 
                           Replicate, 
                           PlantNotes, 
                           SampleType)

# label sample types
strawb_miseq_map$SampleType[strawb_miseq_map$TimePoint == "T0"] <- "post_inoc_pre_stress"
strawb_miseq_map$SampleType[strawb_miseq_map$TimePoint == "T1"] <- "post_inoc_post_stress"
strawb_miseq_map$SampleType[strawb_miseq_map$SampleNotes == "Empty Extraction Tube Control"] <- "DNA_neg"
strawb_miseq_map$SampleType[grep("Inoc", strawb_miseq_map$SampleNotes)] <- "slurry"
strawb_miseq_map$SampleType[strawb_miseq_map$Inoculation == "6"] <- "i6"
strawb_miseq_map$SampleType[grep("Inocolum 6", strawb_miseq_map$SampleNotes)] <- "di_water"
strawb_miseq_map$SampleType[grep("pre-inoc", strawb_miseq_map$SampleNotes)] <- "pre_inoc"

# add empty column for control
strawb_miseq_map <- add_column(strawb_miseq_map, Sample_or_Control = "True Sample")

#label controls (i6, DI water, DNA/PCR negative, pre-inoculated plants)
strawb_miseq_map$Sample_or_Control[strawb_miseq_map$SampleType == "i6"] <- "Control"
strawb_miseq_map$Sample_or_Control[strawb_miseq_map$SampleType == "di_water"] <- "Control"
strawb_miseq_map$Sample_or_Control[strawb_miseq_map$SampleType == "DNA_neg"] <- "Control"
strawb_miseq_map$Sample_or_Control[strawb_miseq_map$SampleType == "pre_inoc"] <- "Control"

# remove unwanted samples
strawb_miseq_map <- strawb_miseq_map[grep("CSIA", strawb_miseq_map$SampleNotes, invert = TRUE),]
strawb_miseq_map <- strawb_miseq_map[strawb_miseq_map$Type != "Palmyra",]

#save new map as a .csv file
write.csv(strawb_miseq_map, "./raw_data/strawb_miseq_map.csv")
```

**Phyloseq**
```{r}

# Hand off to Phyloseq ####
otu <- otu_table(seqtable.nochim,taxa_are_rows = FALSE)
tax <- tax_table(taxa)
met <- sample_data(strawb_miseq_map)
row.names(met) <- strawb_miseq_map$SampleID

ps <- phyloseq(otu,met,tax)

# generate the ASV0001, ASV0002 names
pretty_names <- paste("ASV", sprintf('%0.4d', 1:length(taxa_names(ps))), sep = "")

# reassign the taxa_names from the sequences to the generated ASV names
taxa_names(ps) <- pretty_names

#save phyloseq object
saveRDS(ps, "./intermediate_data/ps.rds")

```
